config/routes.rb
Rails.application.routes.draw do

  root        'tenpo#show'

  resources :tenpos

    resources :projects
end

app/models/project.rb
class Project < ActiveRecord::Base
    validates :shouhin, presence: { message: "商品入力してください" }
    validates :tanka, presence: { message: "単価は半角数字で入力してください" }
    validates :zaikosu, presence: { message: "在庫は半角数字してください" }
    validates :image, presence: { message: "入力してください" }
end

app/models/zzzzz.rb
class Zzzzz < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def index
        @projects = Project.all
    end

    def show
        @project = Project.find(params[:id])
    end

    def new
        @project = Project.new
    end

    def create
        @project = Project.new(project_params)
        if @project.save
            redirect_to projects_path
        else
            render 'new'
        end
    end
    
    def edit
        @project = Project.find(params[:id])
    end

    def update
        @project = Project.find(params[:id])
        if @project.update(project_params)
            redirect_to projects_path
        else
            render 'edit'
        end
    end

    def destroy
        @project = Project.find(params[:id])
        @project.destroy
        redirect_to projects_path
    end

    private
        def project_params
            params[:project].permit(:shouhin, :tanka, :zaikosu, :image)
        end
end

app/controllers/tenpo_controller.rb
class TenpoController < ApplicationController

  def index
    @projects = Project.all
    puts @bentou
  end

  def show
      @projects = Project.all
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tenpo_helper.rb
module TenpoHelper
end

app/views/layouts/_form.html.erb
<%= form_for(@bento) do |f| %>
  <% if @bento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bento.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @bento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field_image">
    <%= image_tag :image %>
  </div>
  
  <div class="field">
    <%= f.label :shouhin %><br>
    <%= f.text_field :shouhin %>
  </div>
  <div class="field">
    <%= f.label :tanka %><br>
    <%= f.number_field :tanka %>
  </div>
  <div class="field">
    <%= f.label :zaikosu %><br>
    <%= f.text_field :zaikosu %>
  </div>
    
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "ほっげほっげ亭" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", media: "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag 'logo2.png', alt: 'ほっげほっげ亭' %>
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "商品一覧", root_path %></li>
            <li><%= link_to "会社概要", root_path %></li>
            <li><%= link_to "お問い合わせ", root_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-md-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-md-3">
          <div class="well sidebar-nav">
            <h3>サイトメニュー</h3>
            <ul class="nav nav-list">
              <li><%= link_to "商品一覧", root_path  %></li>
              <li><%= link_to "会社概要", root_path  %></li>
              <li><%= link_to "お問い合わせ", root_path  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <div class="go-to-top">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-right">
              <%= link_to '#top' do %>
                <i class="fa fa-arrow-circle-up"></i>
                トップへ
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="main">
        <div class="container footer-main">
          <div class="row">
            <div class="col-md-8 text-left hidden-xs">
              <ul class="list-inline">
                <li><%= link_to "商品一覧", root_path %></li>
                <li><%= link_to "会社概要", root_path %></li>
                <li><%= link_to "お問い合わせ", root_path %></li>
                <li><%= link_to "管理者画面", projects_path %></li>
              </ul>
            </div>
            <div class="col-md-4 text-right">
              <p>
                &copy;
                <%= link_to 'Hoggehoggetei', root_path %>
                co., ltd. 2016
              </p>
            </div>
          </div>
        </div>
      </div>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/projects/edit.html.erb
<h1>編集画面  - <%= @project.shouhin %> -</h1>
<%= form_for @project do |f| %>
    <p><%= f.label :商品 %>:<%= f.text_field :shouhin %></p>
    <% if @project.errors.any? %>
        <p class="error"><%= @project.errors.messages[:shouhin][0] %><p>
    <% end %>

    <p><%= f.label :単価 %>:<%= f.text_field :tanka %></p>
    <% if @project.errors.any? %>
        <p class="error"><%= @project.errors.messages[:tanka][0] %><p>
    <% end %>
    
    <p><%= f.label :在庫 %>:<%= f.text_field :zaikosu %></p>
    <% if @project.errors.any? %>
        <p class="error"><%= @project.errors.messages[:zaikosu][0] %><p>
    <% end %>

    <p><%= f.label :画像 %>:<%= f.text_field :image %></p>
    <% if @project.errors.any? %>
        <p class="error"><%= @project.errors.messages[:image][0] %><p>
    <% end %>
    <p><%= f.submit %></p>

<% end %>

<p><%= link_to "新規登録", new_project_path %>　　<%= link_to "管理者画面", projects_path %></p>

app/views/projects/index.html.erb
<h1>管理者画面</h1>
<ul>
    <% @projects.each do |project| %>
    <li><%= link_to project.shouhin, project_path(project.id) %>   <%= link_to "[編集]", edit_project_path(project.id) %>  <%= link_to "[削除]", project_path(project.id), method: :delete, data: { confirm: "よろしいかな？" } %></li>
    
    <% end %>
</ul>
<p><%= link_to "新規登録", new_project_path %>　　<%= link_to "管理者画面", projects_path %></p>

app/views/projects/new.html.erb
<h1>新規登録</h1>





<!--
<%= form_for @project do |f| %>
    <p><%= f.label :商品 %>:<%= f.text_field :shouhin %></p>
    <% if @project.errors.any? %>
        <p class="error"><%= @project.errors.messages[:shouhin][0] %><p>
    <% end %>
    <p><%= f.submit %></p>
<% end %>

<%= form_for @project do |f| %>
    <p><%= f.label :単価 %>:<%= f.text_field :tanka %></p>
    <% if @project.errors.any? %>
        <p class="error"><%= @project.errors.messages[:tanka][0] %><p>
    <% end %>
    <p><%= f.submit %></p>
<% end %>
-->
<%= form_for @project do |f| %>
    <p><%= f.label :商品 %>:<%= f.text_field :shouhin %></p>
    <% if @project.errors.any? %>
        <p class="error"><%= @project.errors.messages[:shouhin][0] %><p>
    <% end %>

    <p><%= f.label :単価 %>:<%= f.text_field :tanka %></p>
    <% if @project.errors.any? %>
        <p class="error"><%= @project.errors.messages[:tanka][0] %><p>
    <% end %>
    
    <p><%= f.label :在庫 %>:<%= f.text_field :zaikosu %></p>
    <% if @project.errors.any? %>
        <p class="error"><%= @project.errors.messages[:zaikosu][0] %><p>
    <% end %>

    <p><%= f.label :画像 %>:<%= f.text_field :image %></p>
    <% if @project.errors.any? %>
        <p class="error"><%= @project.errors.messages[:image][0] %><p>
    <% end %>
    <p><%= f.submit %></p>

<% end %>

<p><%= link_to "新規登録", new_project_path %>　　<%= link_to "管理者画面", projects_path %></p>

app/views/projects/show.html.erb
<h1>商品情報詳細</h1>
<strong>商品名</strong><br>
<%= @project.shouhin %><br>
<strong>単価</strong><br>
<%= @project.tanka %>円<br>
<strong>在庫数</strong><br>
<%= @project.zaikosu %>個<br>
<storong>画像</storong><br>
<img src="<%= @project.image %>" style="width: 150px; height: 100px;"><br>
<%= link_to "[編集]", edit_project_path %>  <%= link_to "[削除]", project_path, method: :delete, data: { confirm: "よろしいかな？" } %></li>
<br>
<br>
<p><%= link_to "新規登録", new_project_path %>　　<%= link_to "管理者画面", projects_path %></p>

app/views/tenpo/_form.html.erb
<%= form_for(@bento) do |f| %>
  <% if @bento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bento.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @bento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field_image">
    <%= image_tag :image %>
  </div>
  
  <div class="field">
    <%= f.label :shouhin %><br>
    <%= f.text_field :shouhin %>
  </div>
  <div class="field">
    <%= f.label :tanka %><br>
    <%= f.number_field :tanka %>
  </div>
  <div class="field">
    <%= f.label :zaikosu %><br>
    <%= f.text_field :zaikosu %>
  </div>
    
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tenpo/edit.html.erb
<h1>Tenpo#edit</h1>

<%= render 'form' %>

<%= link_to 'Show', @bento %> |
<%= link_to 'Back', tenpo_home_path %>

<p>Find me in app/views/tenpo/edit.html.erb</p>​

app/views/tenpo/new.html.erb
<h1>Tenpo#new</h1>

<%= render 'form' %>

<%= link_to 'Show', @bento %> |
<%= link_to 'Back', tenpo_home_path %>


<p>Find me in app/views/tenpo/new.html.erb</p>

app/views/tenpo/show.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

<script type="text/javascript">
//<![CDATA[
$(function(){
    $("button.reset").click(function(){
        $('input[type="text"], input[type="radio"], input[type="checkbox"], select').val("").removeAttr('checked').removeAttr('selected');
    })
})
 
//]]>
</script>


<p id="notice"><%= notice %></p>

<h2>商品一覧<h2>


    <% @projects.each do |project| %>
    <ul style="list-style:none;">
      <li><img src="<%= project.image %>" style="width: 150px; height: 100px;"><%= project.shouhin %> <%= project.tanka %>円 <span style="float: right">
    </ul>
          <!--    
          <li>
            <%= project.shouhin %>
            <%= project.tanka %>円
            <img src="<%= project.image %>" style="width: 150px; height: 100px;">
            <%= project.zaikosu %>
          </li>
          -->      
        
    <% end %>
    

<div class="digest row">
  
  <div class="col-sm-4">
     <%= link_to root_path do %> 
      <h2>ほっげほっげ亭の概要</h2>
      <%= image_tag 'about.png', class: 'img-rounded img-thumbnail' %> 
     <% end %> 
    <p>
      株式会社ほっげほっげ亭についてご紹介いたします。
    </p>
  </div>
</div>